CompileFlags:
  Add: [
    -Wall,
    #-Wextra -Werror,
    -xc++,
    -std=c++11,
    -DCLANGD=1,

    -I.,
    -Ilib,
    -Iinclude,

    -I/home/xbao/lib,

    -DVERBOSE=1,
  ]
  Remove: []

Diagnostics:
  ClangTidy:
    Add: [
      #performance-*,
      #bugprone-*,
      #portability-*,
      #modernize-*,
    ]
    Remove: [
      #misc-definitions-in-headers,
      #modernize-use-trailing-return-type,
    ]
